#!/usr/bin/env bash

# launch the onboard python controller for the cognifly remote control library
# usage:
#   cognifly-controller [--headless]
#
# special bash strings e.g. `&>>` need to be quoted

set -e # exit in case somethings fails

echo "Starting cognifly_controller.py"  # echo the original command

headless=0

echo "hello"
echo "$headless"

for i in "$@" ; do
    if [[ $i == "headless" ]] ; then
        headless=1
        echo "headless mode set"
    fi
done

if $headless
then
  echo "using headless mode"
  python3 -m cognifly controller-headless
else
  echo "using normal mode"
  python3 -m cognifly controller
fi
